### PR TITLE
Added keybord return as a submit

### PR DESCRIPTION
**Pull request by aquacash5**
This will allow users to click the return on the keyboard to submit the prompt

### CODE REVIEW

**Comment by jakallergis** [comment]
Hi @aquacash5 thanks for your 2 cents!
Quick question:
What's the behaviour when you pass `multiline: true` to `textInputProps `? Does it submit when you press return or does it add a new line and nothing more?

**Comment by aquacash5** [comment]
If `multiline: true`, then the `TextInput` will simply ignore the onSubmitEditing action, and the user will have to press the ok button.

**Comment by jakallergis** [comment]
Excellent! Will give it a test and merge it when i find myself some time later today or tomorrow. 
Thanks @aquacash5!

**Comment by aquacash5** [comment]
Not trying to be a pest, but is this going to be merged?

**Comment by jakallergis** [comment]
@aquacash5 thank you for the reminder!
So sorry for the delay, busy days nowadays ¯\_(ツ)_/¯
PR merged, and npm package updated as well! Thanks man

**Pull request merged**
